export default {
    country: [
        "Afghánistán",
        "Alandy",
        "Albánie",
        "Alžírsko",
        "Americká Samoa",
        "Americké Panenské ostrovy",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarktida",
        "Antigua a Barbuda",
        "Argentina",
        "Arménie",
        "Aruba",
        "Austrálie",
        "Ázerbájdžán",
        "Bahamy",
        "Bahrajn",
        "Bangladéš",
        "Barbados",
        "Belgie",
        "Belize",
        "Bělorusko",
        "Benin",
        "Bermudy",
        "Bhútán",
        "Bolívie",
        "Bosna a Hercegovina",
        "Botswana",
        "Bouvetův ostrov",
        "Brazílie",
        "Britské indickooceánské území",
        "Britské Panenské ostrovy",
        "Brunej",
        "Bulharsko",
        "Burkina Faso",
        "Burundi",
        "Čad",
        "Černá Hora",
        "Česko",
        "Chile",
        "Chorvatsko",
        "Čína",
        "Cookovy ostrovy",
        "Dánsko",
        "Dominika",
        "Dominikánská republika",
        "Džibutsko",
        "Egypt",
        "Ekvádor",
        "Eritrea",
        "Estonsko",
        "Etiopie",
        "Faerské ostrovy",
        "Falklandy (Malvíny)",
        "Fidži",
        "Filipíny",
        "Finsko",
        "Francie",
        "Francouzská Guyana",
        "Francouzská jižní území",
        "Francouzská Polynésie",
        "Gabon",
        "Gambie",
        "Ghana",
        "Gibraltar",
        "Grenada",
        "Grónsko",
        "Gruzie",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heardův ostrov a McDonaldovy ostrovy",
        "Honduras",
        "Hongkong",
        "Indie",
        "Indonésie",
        "Irák",
        "Írán",
        "Irsko",
        "Island",
        "Itálie",
        "Izrael",
        "Jamajka",
        "Japonsko",
        "Jemen",
        "Jersey",
        "Jihoafrická republika",
        "Jižní Georgie a Jižní Sandwichovy ostrovy",
        "Jordánsko",
        "Kajmanské ostrovy",
        "Kambodža",
        "Kamerun",
        "Kanada",
        "Kapverdy",
        "Katar",
        "Kazachstán",
        "Keňa",
        "Kiribati",
        "Kokosové (Keelingovy) ostrovy",
        "Kolumbie",
        "Komory",
        "Kongo",
        "Kongo, demokratická republika",
        "Korea, lidově demokratická republika",
        "Korea, republika",
        "Kosovo",
        "Kostarika",
        "Kuba",
        "Kuvajt",
        "Kypr",
        "Kyrgyzstán",
        "Laos",
        "Lesotho",
        "Libanon",
        "Libérie",
        "Libye",
        "Lichtenštejnsko",
        "Litva",
        "Lotyšsko",
        "Lucembursko",
        "Macao",
        "Madagaskar",
        "Maďarsko",
        "Makedonie",
        "Malajsie",
        "Malawi",
        "Maledivy",
        "Mali",
        "Malta",
        "Maroko",
        "Marshallovy ostrovy",
        "Martinik",
        "Mauricius",
        "Mauritánie",
        "Mayotte",
        "Menší odlehlé ostrovy USA",
        "Mexiko",
        "Mikronésie",
        "Moldavsko",
        "Monako",
        "Mongolsko",
        "Montserrat",
        "Mosambik",
        "Myanmar",
        "Namibie",
        "Nauru",
        "Německo",
        "Nepál",
        "Niger",
        "Nigérie",
        "Nikaragua",
        "Niue",
        "Nizozemské Antily",
        "Nizozemsko",
        "Norsko",
        "Nová Kaledonie",
        "Nový Zéland",
        "Omán",
        "Ostrov Man",
        "Ostrov Norfolk",
        "Ostrovy Turks a Caicos",
        "Pákistán",
        "Palau",
        "Palestina",
        "Panama",
        "Papua-Nová Guinea",
        "Paraguay",
        "Peru",
        "Pitcairn",
        "Pobřeží slonoviny",
        "Polsko",
        "Portoriko",
        "Portugalsko",
        "Rakousko",
        "Řecko",
        "Réunion",
        "Rovníková Guinea",
        "Rumunsko",
        "Rusko",
        "Rwanda",
        "Šalamounovy ostrovy",
        "Salvador",
        "Samoa",
        "San Marino",
        "Saúdská Arábie",
        "Senegal",
        "Severní Mariany",
        "Seychely",
        "Sierra Leone",
        "Singapur",
        "Slovensko",
        "Slovinsko",
        "Somálsko",
        "Španělsko",
        "Špicberky a Jan Mayen",
        "Spojené arabské emiráty",
        "Spojené království",
        "Spojené státy americké",
        "Srbsko",
        "Srí Lanka",
        "Středoafrická republika",
        "Súdán",
        "Surinam",
        "Svatá Helena",
        "Svatá Lucie",
        "Svatý Bartoloměj",
        "Svatý Kryštof a Nevis",
        "Svatý Martin",
        "Svatý Pierre a Miquelon",
        "Svatý stolec (Vatikánský městský stát)",
        "Svatý Tomáš a Princův ostrov",
        "Svatý Vincenc a Grenadiny",
        "Svazijsko",
        "Švédsko",
        "Švýcarsko",
        "Sýrie",
        "Tádžikistán",
        "Tanzanie",
        "Tchaj-wan",
        "Thajsko",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad a Tobago",
        "Tunisko",
        "Turecko",
        "Turkmenistán",
        "Tuvalu",
        "Uganda",
        "Ukrajina",
        "Uruguay",
        "Uzbekistán",
        "Vánoční ostrovy",
        "Vanuatu",
        "Venezuela",
        "Vietnam",
        "Východní Timor",
        "Wallis a Futuna",
        "Zambie",
        "Západní Sahara",
        "Zimbabwe"
    ]
}